### ISSUE TITLE
As a data curator, I want to run basic data validation on files while on Tigress, without having to download them to my local machine

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/dspace-development#271]
Sub-tickets are tracked in this repo: https://github.com/pulibrary/prds-validate-csv, but the main epics are:
- [ ] Create a command-line tool that applies both LOC’s RFC 4180 guidelines and PRDS’s own validation requirements to a given CSV
- [ ] Get repo up and running on Tigress
- [ ] Train PRDS on using this tool as well as `less` and `head` to help them work in the shell.

**Comment by kmcelwee** [comment]
Per PRDS, this is not a priority right now.

**Comment by hhkitsune** [comment]
Resolved by what has been implemented by [https://github.com/pulibrary/prds-validate-csv](https://github.com/pulibrary/prds-validate-csv)
