### ISSUE TITLE
Execute the Elements Migration Tasks (detailed by Digital Science) and provide updates to the Digital Science team

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#647]
The following issues are required to be completed by the Digital Science team undertaking the migration for the Symplectic Elements `development` and `production` deployments.

## Building Elements environment(s)
- [ ] Princeton to provide SMTP credentials (if required) https://github.com/pulibrary/dspace-development/issues/648

## Preparation
- [ ] Symplectic and Princeton to define the environment connections https://github.com/pulibrary/dspace-development/issues/649

## Provisioning infrastructure
- [ ] Princeton to upload the custom SSRS reports to the AWS S3 bucket https://github.com/pulibrary/dspace-development/issues/650

## Switch over phase - Non-Prod instance(s)
- [ ] Princeton to stop services and put 'on-premise' NON-Production Elements in maintenance mode https://github.com/pulibrary/dspace-development/issues/651
- [ ] Princeton to take final Elements backup from Production environment and upload to AWS S3 bucket https://github.com/pulibrary/dspace-development/issues/652
- [ ] Princeton to commit DNS changes https://github.com/pulibrary/dspace-development/issues/653

## Switch over phase - Production
- [ ] Princeton to confirm TTL for DNS is set to 5 mins https://github.com/pulibrary/dspace-development/issues/654
- [ ] Princeton to stop services and put 'old' Production in maintenance mode https://github.com/pulibrary/dspace-development/issues/655
- [ ] Princeton to take final Elements backup from Production environment and upload to AWS S3 bucket https://github.com/pulibrary/dspace-development/issues/652
- [ ] Princeton to commit DNS changes - Hosted Elements Go-Live https://github.com/pulibrary/dspace-development/issues/657

## Testing the Hosted Elements instance(s)
- [x] Princeton to test access to the Reporting Database and SSRS https://github.com/pulibrary/dspace-development/issues/658
- [x] Princeton to test Repository Connections https://github.com/pulibrary/dspace-development/issues/659
- [x] Princeton to test registered reports in Elements https://github.com/pulibrary/dspace-development/issues/660
- [x] Princeton to test the new instance and provide feedback https://github.com/pulibrary/dspace-development/issues/661
- [ ] Princeton to announce service downtime to use https://github.com/pulibrary/dspace-development/issues/662
